name: Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Platane/snk@v2
        with:
          github_user_name: V1ct0rhugo22
          svg_out_path: ./assets/github-snake.svg
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: assets
