name: Snake Animation
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [main]

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: V1ct0rhugo22
          svg_out_path: ./snake.svg
          
      - name: Commit and Push
        run: |
          git config --global user.name "V1ct0rhugo22"
          git config --global user.email "victorhero53@gmail.com"
          git add snake.svg
          git commit -m "Update snake animation"
          git push
